-- ============================================
-- TABELA DE USUÁRIOS
-- ============================================

CREATE TABLE usuarios (
    id                  BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome_completo       VARCHAR(64) NOT NULL,
    email               VARCHAR(64) NOT NULL UNIQUE,
    senha_hash          VARCHAR(512) NOT NULL,
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email_verificado    BOOLEAN NOT NULL DEFAULT FALSE,
    perfil              VARCHAR(16) CHECK (perfil IN ('aluno', 'administrador')) NOT NULL,

    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);


-- ============================================
-- TABELA DE ALUNOS
-- ============================================

CREATE TABLE alunos (
    id                  BIGINT PRIMARY KEY,
    vidas               BIGINT NOT NULL,
    sequencia           BIGINT NOT NULL,
    data_nascimento     DATE NOT NULL,
    apelido             VARCHAR(16) NOT NULL UNIQUE,
    genero              VARCHAR(16) CHECK (genero IN ('feminino', 'masculino', 'outro')),
    telefone            VARCHAR(15),
    imagem_perfil_url   TEXT,

    FOREIGN KEY (id) REFERENCES usuarios(id) ON DELETE CASCADE
);


-- ============================================
-- TABELA DE ADMINISTRADORES
-- ============================================

CREATE TABLE administradores (
    id                  BIGINT PRIMARY KEY,
    nivel_administrador INT DEFAULT 1,

    FOREIGN KEY (id) REFERENCES usuarios(id) ON DELETE CASCADE
);


-- ============================================
-- TABELA DE CURSOS
-- ============================================

CREATE TABLE cursos (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR(64) NOT NULL,
    descricao       TEXT
);


-- ============================================
-- TABELA DE SEÇÕES
-- ============================================

CREATE TABLE secoes (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    curso_id        BIGINT NOT NULL,
    titulo          VARCHAR(64) NOT NULL,
    posicao         INT NOT NULL,
    descricao       TEXT,

    FOREIGN KEY (curso_id) REFERENCES cursos(id) ON DELETE CASCADE
);


-- ============================================
-- TABELA DE LIÇÕES
-- ============================================

CREATE TABLE licoes (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    secao_id        BIGINT NOT NULL,
    titulo          VARCHAR(64) NOT NULL,
    posicao         INT NOT NULL,
    bloqueada       BOOLEAN DEFAULT TRUE,

    FOREIGN KEY (secao_id) REFERENCES secoes(id) ON DELETE CASCADE
);


-- ============================================
-- TABELA DE TIPOS DE QUESTÃO
-- ============================================

CREATE TABLE tipos_questao (
    id              SMALLINT PRIMARY KEY,
    nome            VARCHAR(32) CHECK (
        nome IN ('aberta', 'multipla_escolha', 'associacao')
    ) NOT NULL
);


-- ============================================
-- TABELA DE QUESTÕES
-- ============================================

CREATE TABLE questoes (
    id              BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    enunciado       TEXT NOT NULL,
    tipo_id         SMALLINT NOT NULL,
    licao_id        BIGINT,

    CONSTRAINT pk_questoes PRIMARY KEY (id),

    FOREIGN KEY (tipo_id)
        REFERENCES tipos_questao(id),

    FOREIGN KEY (licao_id)
        REFERENCES licoes(id)
        ON DELETE CASCADE
);


-- ============================================
-- TABELA DE QUESTÕES ABERTAS
-- ============================================

CREATE TABLE questoes_abertas (
    id                  BIGINT PRIMARY KEY,
    resposta_correta   TEXT NOT NULL,
    conteudo            TEXT NOT NULL,
    tipo_conteudo       VARCHAR(16) NOT NULL CHECK (
        tipo_conteudo IN ('texto', 'video', 'imagem', 'audio')
    ),

    FOREIGN KEY (id)
        REFERENCES questoes(id)
        ON DELETE CASCADE
);


-- ============================================
-- TABELA DE QUESTÕES DE ASSOCIAÇÃO
-- ============================================

CREATE TABLE questoes_associativas (
    id                  BIGINT PRIMARY KEY,

    FOREIGN KEY (id)
        REFERENCES questoes(id)
        ON DELETE CASCADE
);


-- ============================================
-- TABELA DE ITENS DAS QUESTÕES DE ASSOCIAÇÃO
-- ============================================

CREATE TABLE itens_associativos (
    id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conteudo            TEXT NOT NULL,
    tipo_conteudo       VARCHAR(16) NOT NULL CHECK (
        tipo_conteudo IN ('texto', 'video', 'imagem', 'audio')
    ),
    tipo_coluna         CHAR NOT NULL CHECK (
        tipo_coluna IN ('A', 'B')
    ),
    questao_id          BIGINT NOT NULL,

    FOREIGN KEY (questao_id)
        REFERENCES questoes_associativas(id)
        ON DELETE CASCADE
);


-- ============================================
-- TABELA DE PARES DAS QUESTÕES DE ASSOCIAÇÃO
-- ============================================

CREATE TABLE pares_associativos (
    id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_esquerdo_id    BIGINT NOT NULL,
    item_direito_id     BIGINT NOT NULL,

    UNIQUE (item_esquerdo_id, item_direito_id),

    FOREIGN KEY (item_esquerdo_id)
        REFERENCES itens_associativos(id)
        ON DELETE CASCADE,

    FOREIGN KEY (item_direito_id)
        REFERENCES itens_associativos(id)
        ON DELETE CASCADE
);


-- ============================================
-- TABELA DE QUESTÕES DE MÚLTIPLA ESCOLHA
-- ============================================

CREATE TABLE questoes_multipla_escolha (
    id                  BIGINT PRIMARY KEY,
    conteudo            TEXT NOT NULL,
    tipo_conteudo       VARCHAR(16) NOT NULL CHECK (
        tipo_conteudo IN ('texto', 'video', 'imagem', 'audio')
    ),

    FOREIGN KEY (id)
        REFERENCES questoes(id)
        ON DELETE CASCADE
);


-- ============================================
-- TABELA DE OPÇÕES DAS QUESTÕES
-- ============================================

CREATE TABLE opcoes_questao (
    id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    questao_id          BIGINT NOT NULL,
    conteudo            TEXT NOT NULL,
    tipo_conteudo       VARCHAR(16) NOT NULL CHECK (
        tipo_conteudo IN ('texto', 'video', 'imagem', 'audio')
    ),
    correta             BOOLEAN NOT NULL DEFAULT FALSE,

    FOREIGN KEY (questao_id)
        REFERENCES questoes_multipla_escolha(id)
        ON DELETE CASCADE
);


-- ============================================
-- TABELA DE RESPOSTAS
-- ============================================

CREATE TABLE respostas (
    id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    questao_id          BIGINT NOT NULL,
    aluno_id            BIGINT NOT NULL,
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correta             BOOLEAN NOT NULL,

    FOREIGN KEY (questao_id)
        REFERENCES questoes(id)
        ON DELETE CASCADE,

    FOREIGN KEY (aluno_id)
        REFERENCES alunos(id)
        ON DELETE CASCADE
);


-- ============================================
-- TABELA DE RESPOSTAS DE MÚLTIPLA ESCOLHA
-- ============================================

CREATE TABLE respostas_multipla_escolha (
    id                  BIGINT PRIMARY KEY,
    opcao_selecionada_id BIGINT NOT NULL,

    FOREIGN KEY (id)
        REFERENCES respostas(id)
        ON DELETE CASCADE,

    FOREIGN KEY (opcao_selecionada_id)
        REFERENCES opcoes_questao(id)
);


-- ============================================
-- TABELA DE RESPOSTAS ABERTAS
-- ============================================

CREATE TABLE respostas_abertas (
    id                  BIGINT PRIMARY KEY,
    resposta_texto      TEXT NOT NULL,

    FOREIGN KEY (id)
        REFERENCES respostas(id)
        ON DELETE CASCADE
);


-- ============================================
-- TABELA DE RESPOSTAS DE ASSOCIAÇÃO
-- ============================================

CREATE TABLE respostas_associacao (
    id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_esquerdo_id    BIGINT NOT NULL,
    item_direito_id     BIGINT NOT NULL,
    resposta_id         BIGINT NOT NULL,

    FOREIGN KEY (resposta_id)
        REFERENCES respostas(id)
        ON DELETE CASCADE,

    FOREIGN KEY (item_esquerdo_id)
        REFERENCES itens_associativos(id),

    FOREIGN KEY (item_direito_id)
        REFERENCES itens_associativos(id)
);


-- ============================================
-- TABELA DE PROGRESSO DAS QUESTÕES
-- ============================================

CREATE TABLE progresso_questao (
    aluno_id            BIGINT,
    questao_id          BIGINT,
    tentativas          INT DEFAULT 0,
    correta             BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (aluno_id, questao_id),

    FOREIGN KEY (aluno_id)
        REFERENCES alunos(id),

    FOREIGN KEY (questao_id)
        REFERENCES questoes(id)
        ON DELETE CASCADE
);
