-- Tabela de usuário
CREATE TABLE users (
    user_id           BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    full_name              VARCHAR(64) NOT NULL,
    email             VARCHAR(64) NOT NULL UNIQUE,
    password_hash     VARCHAR(512) NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email_verified    BOOLEAN NOT NULL DEFAULT false,
    role VARCHAR(16) CHECK (role IN ('student', 'admin')),

    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

-- Tabela de alunos
    CREATE TABLE students (
    student_id             BIGINT PRIMARY KEY,
    lives                  BIGINT NOT NULL,
    streak                 BIGINT NOT NULL,
    birth_date             DATE NOT NULL,
    nickname               VARCHAR(16) NOT NULL UNIQUE,
    gender                 VARCHAR(16) CHECK (gender IN ('female','male','other')),
    phone_number           VARCHAR(15),
    profile_image_url      TEXT,

    FOREIGN KEY (student_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Tabela de administradores
    CREATE TABLE admins (
    admin_id BIGINT PRIMARY KEY,
    admin_level INT DEFAULT 1,
    FOREIGN KEY (admin_id) REFERENCES users(user_id) ON DELETE CASCADE
    );

-- Tabela de curso
CREATE TABLE courses (
    course_id     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(64) NOT NULL, -- ex: "Libras Básico"
    description   TEXT
);

-- Tabela de seções
CREATE TABLE sections (
    section_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    course_id     BIGINT NOT NULL,
    title         VARCHAR(64) NOT NULL, -- ex: "Saudações"
    position      INT NOT NULL, -- ordem

    FOREIGN KEY (course_id) REFERENCES courses(course_id) ON DELETE CASCADE
);

-- Tabela de lições
CREATE TABLE lessons (
    lesson_id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    section_id     BIGINT NOT NULL,
    title          VARCHAR(64) NOT NULL, -- ex: "Cumprimentos básicos"
    position       INT NOT NULL,
    is_locked      BOOLEAN DEFAULT TRUE

    FOREIGN KEY (section_id) REFERENCES sections(section_id) ON DELETE CASCADE
);

-- Tabela de tipo de questão
CREATE TABLE question_types (
    question_type_id    SMALLINT PRIMARY KEY,
    name                VARCHAR(32) UNIQUE NOT NULL
);

-- Tabela de questões
CREATE TABLE questions  (
    question_id     BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    statement       TEXT NOT NULL,
    type_id         SMALLINT NOT NULL,
    lesson_id       BIGINT,

    CONSTRAINT pk_question PRIMARY KEY (question_id),
    FOREIGN KEY (type_id) REFERENCES question_types(question_type_id),
    FOREIGN KEY (lesson_id) REFERENCES lessons(lesson_id) ON DELETE CASCADE
);

-- Tabela de questão associativa
CREATE TABLE question_pairs (
    question_pair_id     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question_id          BIGINT NOT NULL,
    left_text            VARCHAR(255) NOT NULL, -- ex: palavra em português
    right_video_url      TEXT NOT NULL, -- ex: vídeo do sinal

    FOREIGN KEY (question_id) REFERENCES questions(question_id) ON DELETE CASCADE
);

-- Tabela de opção para questões de múltipla escolha
CREATE TABLE question_options (
    option_id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question_id              BIGINT NOT NULL,
    content                  TEXT NOT NULL, -- texto ou URL (imagem/vídeo)
    content_type             VARCHAR(16) NOT NULL CHECK (content_type IN ('text','video','image')),
    is_correct               BOOLEAN NOT NULL DEFAULT FALSE,

    FOREIGN KEY (question_id) REFERENCES questions(question_id) ON DELETE CASCADE
);

-- Tabela de respostas de usuários para questões de múltipla escolha
CREATE TABLE user_option_answers (
    option_answer_id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id                  BIGINT NOT NULL,
    question_id              BIGINT NOT NULL,
    question_options_id      BIGINT NOT NULL,

    UNIQUE (user_id, question_id, question_options_id),

    FOREIGN KEY (question_options_id) REFERENCES question_options(option_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (question_id) REFERENCES questions(question_id) ON DELETE CASCADE
);

-- Tabela de questões de respostas abertas
CREATE TABLE question_answers (
    question_answers_id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question_id                 BIGINT NOT NULL,
    answer_text                 TEXT NOT NULL,

    FOREIGN KEY (question_id) REFERENCES questions(question_id) ON DELETE CASCADE
);

-- Tabela de respostas de usuários para questões de respostas abertas
CREATE TABLE user_text_answers (
    text_answer_id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id                  BIGINT NOT NULL,
    question_id              BIGINT NOT NULL,
    user_answer              TEXT NOT NULL,
    is_correct               BOOLEAN,

    FOREIGN KEY (question_id) REFERENCES questions(question_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Tabela de progresso
CREATE TABLE user_question_progress (
    user_id       BIGINT,
    question_id   BIGINT,
    attempts      INT DEFAULT 0,
    correct       BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (user_id, question_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (question_id) REFERENCES questions(question_id) ON DELETE CASCADE
);