-- Tabela de usuário
CREATE TABLE users (
    id                     BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    full_name              VARCHAR(64) NOT NULL,
    email                  VARCHAR(64) NOT NULL UNIQUE,
    password_hash          VARCHAR(512) NOT NULL,
    created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email_verified         BOOLEAN NOT NULL DEFAULT false,
    role                   VARCHAR(16) CHECK (role IN ('student', 'admin')) NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Tabela de alunos
    CREATE TABLE students (
    id                     BIGINT PRIMARY KEY,
    lives                  BIGINT NOT NULL,
    streak                 BIGINT NOT NULL,
    birth_date             DATE NOT NULL,
    nickname               VARCHAR(16) NOT NULL UNIQUE,
    gender                 VARCHAR(16) CHECK (gender IN ('female','male','other')),
    phone_number           VARCHAR(15),
    profile_image_url      TEXT,

    FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabela de administradores
    CREATE TABLE admins (
    id              BIGINT PRIMARY KEY,
    admin_level     INT DEFAULT 1,
    FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
    );

-- Tabela de curso
CREATE TABLE courses (
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(64) NOT NULL, -- ex: "Libras Básico"
    description   TEXT
);

-- Tabela de seções
CREATE TABLE sections (
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    course_id     BIGINT NOT NULL,
    title         VARCHAR(64) NOT NULL, -- ex: "Saudações"
    position      INT NOT NULL, -- ordem
    description   TEXT,

    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

-- Tabela de lições
CREATE TABLE lessons (
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    section_id     BIGINT NOT NULL,
    title          VARCHAR(64) NOT NULL, -- ex: "Cumprimentos básicos"
    position       INT NOT NULL,
    is_locked      BOOLEAN DEFAULT TRUE,

    FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE
);

-- Tabela de tipo de questão
CREATE TABLE question_types (
    id         SMALLINT PRIMARY KEY,
    name       VARCHAR(32) CHECK (name IN ('open','options','association')) NOT NULL
);

-- Tabela de questões
CREATE TABLE questions  (
    id              BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    statement       TEXT NOT NULL,
    type_id         SMALLINT NOT NULL,
    lesson_id       BIGINT,

    CONSTRAINT pk_question PRIMARY KEY (id),
    FOREIGN KEY (type_id) REFERENCES question_types(id),
    FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE
);

-- Tabela de questões abertas
CREATE TABLE open_questions (
    id                 BIGINT PRIMARY KEY,
    correct_answer     TEXT NOT NULL,
    content            TEXT NOT NULL,
    content_type       VARCHAR(16) NOT NULL CHECK (content_type IN ('text','video','image', 'audio')),

    FOREIGN KEY (id) REFERENCES questions(id) ON DELETE CASCADE
);

-- Tabela de questões associativas
CREATE TABLE associative_questions (
    id      BIGINT PRIMARY KEY,

    FOREIGN KEY (id) REFERENCES questions(id) ON DELETE CASCADE
);

-- Tabela de item de questões associativas
CREATE TABLE associative_items (
    id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content             TEXT NOT NULL,
    content_type        VARCHAR(16) NOT NULL CHECK (content_type IN ('text','video','image', 'audio')),
    column_type         CHAR NOT NULL CHECK (column_type IN ('A', 'B')),
    question_id         BIGINT NOT NULL,

    FOREIGN KEY (question_id) REFERENCES associative_questions(id) ON DELETE CASCADE
);

-- Tabela de pares de questões associativas
    CREATE TABLE associative_pairs (
    id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    left_item_id        BIGINT NOT NULL,
    right_item_id       BIGINT NOT NULL,

    UNIQUE(left_item_id, right_item_id),
    FOREIGN KEY (left_item_id) REFERENCES associative_items(id) ON DELETE CASCADE,
    FOREIGN KEY (right_item_id) REFERENCES associative_items(id) ON DELETE CASCADE
    );



-- Tabela de questão de múltipla escolha
CREATE TABLE multiple_choice_questions (
    id                  BIGINT PRIMARY KEY,
    content             TEXT NOT NULL,
    content_type        VARCHAR(16) NOT NULL CHECK (content_type IN ('text','video','image', 'audio')),

    FOREIGN KEY (id) REFERENCES questions(id) ON DELETE CASCADE
);

-- Tabela de opções para questões de múltipla escolha
CREATE TABLE question_options (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question_id              BIGINT NOT NULL,
    content                  TEXT NOT NULL, -- texto ou URL (imagem/vídeo)
    content_type             VARCHAR(16) NOT NULL CHECK (content_type IN ('text','video','image', 'audio')),
    is_correct               BOOLEAN NOT NULL DEFAULT FALSE,

    FOREIGN KEY (question_id) REFERENCES multiple_choice_questions(id) ON DELETE CASCADE
);

-- Tabela de respostas
CREATE TABLE answers (
    id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question_id        BIGINT NOT NULL,
    student_id            BIGINT NOT NULL,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_correct         BOOLEAN NOT NULL,

    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

-- Tabela de respostas de usuários para questões de múltipla escolha
CREATE TABLE multiple_choice_answers (
    id                     BIGINT PRIMARY KEY,
    selected_option_id     BIGINT NOT NULL,

    FOREIGN KEY (id) REFERENCES answers(id) ON DELETE CASCADE,
    FOREIGN KEY (selected_option_id) REFERENCES question_options(id)
);

-- Tabela de respostas de usuários para questões de respostas abertas
CREATE TABLE open_answers (
    id                BIGINT PRIMARY KEY,
    text_answer       TEXT NOT NULL,

    FOREIGN KEY (id) REFERENCES answers(id) ON DELETE CASCADE
);

-- Tabela de respostas de usuários para questões de associação
CREATE TABLE matching_answers (
    id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    left_item_id       BIGINT NOT NULL,
    right_item_id      BIGINT NOT NULL,
    answer_id          BIGINT NOT NULL,

    FOREIGN KEY (answer_id) REFERENCES answers(id) ON DELETE CASCADE,
    FOREIGN KEY (left_item_id) REFERENCES associative_items(id),
    FOREIGN KEY (right_item_id) REFERENCES associative_items(id)
);

-- Tabela de progresso
CREATE TABLE question_progress (
    student_id    BIGINT,
    question_id   BIGINT,
    attempts      INT DEFAULT 0,
    correct       BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (student_id, question_id),
    FOREIGN KEY (student_id) REFERENCES students(id),
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);