CREATE TABLE users (
    id              BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lives           BIGINT NOT NULL,
    email           VARCHAR(50) NOT NULL,
    streak          BIGINT NOT NULL,
    full_name       VARCHAR(100) NOT NULL,
    nickname        VARCHAR(20) NOT NULL,
    gender          CHAR NOT NULL,
    phone_number    VARCHAR(15),
    birth_date      DATE NOT NULL
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE question  (
    id              BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    statement       VARCHAR(550) NOT NULL,
    type            VARCHAR(10) NOT NULL,
    answer_id       BIGINT NOT NULL,
    CONSTRAINT pk_question PRIMARY KEY (id)
);

CREATE TABLE alternative  (
    id                               BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    visual_id                        VARCHAR(550),
    text                             VARCHAR(10),
    corresponding_alternative_id     BIGINT,
    question_id                      BIGINT NOT NULL,
    CONSTRAINT pk_alternative PRIMARY KEY (id),
    CONSTRAINT fk_alternative_on_question FOREIGN KEY(question_id) REFERENCES question(id)
);
